config/routes.rb
CARS::Application.routes.draw do
  root "home#index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  resources :users, only: [:index, :show]

  resources :enrollments do
   resources :attendances
   resources :course_progresses
  end

  resources :sections do
    resources :enrollments
    resources :attendances do
      collection do
        post 'take'
      end
    end
  end

  resources :employees, except: [:index, :new, :create, :destroy] do
    resources :sections
  end

  resources :customers, except: [:index, :new, :create, :destroy] do
    resources :transactions do
      resource :transactions
    end
    resources :enrollments do
      resources :attendances
    end
  end

  resources :courses do
    resources :sections, :course_prerequisites, :instruction_units
  end

  

end

app/models/course_prerequisite.rb
class CoursePrerequisite < ActiveRecord::Base
  belongs_to :course
  belongs_to :prerequisite, :class_name => 'Course'

  validates_associated :course
  validates_associated :prerequisite
  validates_inclusion_of :allow_concurrent, :in => [true, false]
  validates_uniqueness_of :prerequisite, :scope => :course
  
  def allow_concurrent?
    self.allow_concurrent
  end
end

app/controllers/course_prerequisites_controller.rb
class CoursePrerequisitesController < ApplicationController
  before_action :set_course_prerequisite, only: [:show, :edit, :update, :destroy]
  before_filter do
    @course = Course.find(params[:course_id])
  end

  # GET /course_prerequisites
  # GET /course_prerequisites.json
  def index
    @course_prerequisites = CoursePrerequisite.all
  end

  # GET /course_prerequisites/1
  # GET /course_prerequisites/1.json
  def show
  end

  # GET /course_prerequisites/new
  def new
    @course_prerequisite = CoursePrerequisite.new
  end

  # GET /course_prerequisites/1/edit
  def edit
  end

  # POST /course_prerequisites
  # POST /course_prerequisites.json
  def create
    @course_prerequisite = CoursePrerequisite.new(course_prerequisite_params)

    respond_to do |format|
      if @course_prerequisite.save
        format.html { redirect_to [@course, @course_prerequisite], notice: 'Course prerequisite was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@course,@course_prerequisite] }
      else
        format.html { render action: 'new' }
        format.json { render json: @course_prerequisite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_prerequisites/1
  # PATCH/PUT /course_prerequisites/1.json
  def update
    respond_to do |format|
      if @course_prerequisite.update(course_prerequisite_params)
        format.html { redirect_to [@course,@course_prerequisite], notice: 'Course prerequisite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course_prerequisite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_prerequisites/1
  # DELETE /course_prerequisites/1.json
  def destroy
    @course_prerequisite.destroy
    respond_to do |format|
      format.html { redirect_to course_course_prerequisites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_prerequisite
      @course_prerequisite = CoursePrerequisite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_prerequisite_params
      params.require(:course_prerequisite).permit(:allow_concurrent)
    end
end

app/helpers/course_prerequisites_helper.rb
module CoursePrerequisitesHelper
end

app/views/course_prerequisites/_form.html.erb
<%= form_for([@course, @course_prerequisite]) do |f| %>
  <% if @course_prerequisite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_prerequisite.errors.count, "error") %> prohibited this course_prerequisite from being saved:</h2>

      <ul>
      <% @course_prerequisite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4><%= @course.name %> <%= f.select :allow_concurrent, { 'Can' => true, 'Cannot' => false } %> be take concurrently with <%= @course_prerequisite.prerequisite.name %></h4>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/course_prerequisites/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', course_course_prerequisite_path(@course, @course_prerequisite) %> |
<%= link_to 'Back', course_course_prerequisites_path %>

app/views/course_prerequisites/index.html.erb
<h1>Listing course_prerequisites</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Course</th>
      <th>Prerequisite Course</th>
      <th>Concurrent Enrollment?</th>
    </tr>
  </thead>

  <tbody>
    <% @course_prerequisites.each do |course_prerequisite| %>
      <tr>
        <td><%= course_prerequisite.course.name %></td>
        <td><%= course_prerequisite.prerequisite.name %></td>
        <td><%= course_prerequisite.allow_concurrent.to_s.upcase %></td>
        <td><%= link_to 'Show', course_course_prerequisite_path(course_prerequisite.course, course_prerequisite.prerequisite) %></td>
        <td><%= link_to 'Edit', edit_course_course_prerequisite_path(course_prerequisite.course, course_prerequisite.prerequisite) %></td>
        <td><%= link_to 'Destroy', course_course_prerequisite_path(course_prerequisite.course, course_prerequisite.prerequisite), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course prerequisite', new_course_course_prerequisite_path %>

app/views/course_prerequisites/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', course_course_prerequisites_path %>

app/views/course_prerequisites/show.html.erb
<p id="notice"><%= notice %></p>
<h4><%= "#{@course.name} #{@course_prerequisite.allow_concurrent ? 'CAN' : 'CANNOT'} be take concurrently with #{@course_prerequisite.prerequisite.name}" %></h4>
<%= link_to 'Edit', edit_course_course_prerequisite_path(@course,@course_prerequisite) %> |
<%= link_to 'Back', course_course_prerequisites_path %>