config/routes.rb
CARS::Application.routes.draw do
  root "home#index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  resources :users, only: [:index, :show]

  resources :enrollments do
   resources :attendances
   resources :course_progresses
  end

  resources :sections do
    resources :enrollments
    resources :attendances do
      collection do
        post 'take'
      end
    end
  end

  resources :employees, except: [:index, :new, :create, :destroy] do
    resources :sections
  end

  resources :customers, except: [:index, :new, :create, :destroy] do
    resources :transactions do
      resource :transactions
    end
    resources :enrollments do
      resources :attendances
    end
  end

  resources :courses do
    resources :sections, :course_prerequisites, :instruction_units
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  belongs_to :last_name_suffix
  belongs_to :state
  belongs_to :salutation


  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :home_phone, :presence => true, format: { with: /\A\d{3}-\d{3}-\d{4}\z/, message: "- bad format. Please use: 123-456-7890" }
  validates :cell_phone, :presence => true, format: { with: /\A\d{3}-\d{3}-\d{4}\z/, message: "- bad format. Please use: 123-456-7890" }
  validates :address, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :postal_code, :presence => true, format: { with: /\A\d{5}(-\d{4})?\z/, message: "- bad format. Please use: 12345 or 12345-6789" }
  validates :dob, :presence => true
  validates :salutation, :presence => true

  validates :type, :presence => true
  validates_inclusion_of :type, :in => %w( Customer Employee )

  #Method that returns if the logged in user is an employee.
  def is_employee?
    self.type == 'Employee' ? true : false
  end

  #Method that returns if the logged in user is a customer.
  def is_customer?
    self.type == 'Customer' ? true : false
  end

  def full_name
    self.salutation.name + ' ' \
    + self.first_name + ' ' \
    + self.last_name \
    + (self.last_name_suffix.nil? ? '' : ', ' + self.last_name_suffix.name)
  end

  def full_address
    self.address + '<br/>' \
    + (self.address2.nil? ? '' : ' ' + self.address2) \
    + self.city + ' ' + self.state.abbr + ', ' + self.postal_code
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.is_customer?
        format.html {redirect_to customer_path(@user)}
      else
        format.html {redirect_to employee_path(@user)}
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :last_name_suffix_id, :home_phone, :cell_phone, :address, :address2, :city, :state_id, :postal_code, :dob, :salutation_id, :type)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for (@customer || @employee), :html => { :class => 'form-horizontal' } do |f| %>
    <div class='well' style="height: 450px">
      <div id='registration_form1'>

        <div class="field">
          <%= f.label :email %>
          <br/>
          <%= f.email_field :email, :autofocus => true %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <br/>
          <%= f.password_field :password, :autocomplete => "off" %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %>
          <br/>
          <%= f.password_field :password_confirmation, :autocomplete => "off" %>
        </div>
        <div class="field">
          <%= f.label :dob, :dob.to_s.upcase %>
          <br>
          <%= f.text_field :dob, :class => 'datepicker', :readonly => true %>
        </div>

        <button id='registration_form1_next' class='btn btn-small btn-info'>Next &rarr;</button>
      </div>

      <div id='registration_form2'>
        <div class="field">
          <%= f.label :salutation %>
          <br>
          <%= f.select(:salutation_id, Salutation.all.map { |s| [s.name, s.id] }) %>
        </div>
        <div class="field">
          <%= f.label :first_name %>
          <br>
          <%= f.text_field :first_name %>
        </div>
        <div class="field">
          <%= f.label :last_name %>
          <br>
          <%= f.text_field :last_name %>
        </div>
        <div class="field">
          <%= f.label :last_name_suffix_id %>
          <br>
          <%= f.select(:last_name_suffix_id, LastNameSuffix.all.map { |lns| [lns.name, lns.id] }, :include_blank => true) %>
        </div>
        <button id='registration_form2_previous' class='btn btn-small btn-info'>&larr; Previous</button>
        <button id='registration_form2_next' class='btn btn-small btn-info'>Next &rarr;</button>
      </div>

      <div id='registration_form3'>
        <div class="field">
          <%= f.label :home_phone %>
          <br/>
          <%= f.text_field :home_phone %>
          <sub> Format: 123-456-7890</sub>
        </div>
        <div class="field">
          <%= f.label :cell_phone %>
          <br/>
          <%= f.text_field :cell_phone %>
          <sub> Format: 123-456-7890</sub>
        </div>
        <button id='registration_form3_previous' class='btn btn-small btn-info'>&larr; Previous</button>
        <button id='registration_form3_next' class='btn btn-small btn-info'>Next &rarr;</button>
      </div>

      <div id='registration_form4'>
        <div class="field">
          <%= f.label :address %>
          <br>
          <%= f.text_field :address %>
        </div>
        <div class="field">
          <%= f.label :address2 %>
          <br>
          <%= f.text_field :address2 %>
        </div>
        <div class="field">
          <%= f.label :city %>
          <br>
          <%= f.text_field :city %>
        </div>
        <div class="field">
          <%= f.label :state %>
          <br>
          <%= f.select(:state_id, State.all.map { |s| [s.name, s.id] }) %>
        </div>
        <div class="field">
          <%= f.label :postal_code %>
          <br/>
          <%= f.text_field :postal_code %>
          <sub> Format: 12345 or 12345-6789</sub>
        </div>
        <button id='registration_form4_previous' class='btn btn-small btn-info'>&larr; Previous</button>
      </div>
    </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn' %>
  </div>
<% end %>

<script>
    $('document').ready(function(){

        function set_form(form_h, form_s){
            form_s.show();
            if (form_h){ form_h.hide()};
            bind_buttons();
        }

        function bind_buttons(){
            $('#registration_form1_next').on('click', function(e){
                e.preventDefault();
                set_form($('#registration_form1'),$('#registration_form2'));
            });

            $('#registration_form2_previous').on('click', function(e){
                e.preventDefault();
                set_form($('#registration_form2'),$('#registration_form1'));
            });
            $('#registration_form2_next').on('click', function(e){
                e.preventDefault();
                set_form($('#registration_form2'),$('#registration_form3'));
            });

            $('#registration_form3_previous').on('click', function(e){
                e.preventDefault();
                set_form($('#registration_form3'),$('#registration_form2'));
            });
            $('#registration_form3_next').on('click', function(e){
                e.preventDefault();
                set_form($('#registration_form3'),$('#registration_form4'));
            });

            $('#registration_form4_previous').on('click', function(e){
                e.preventDefault();
                set_form($('#registration_form4'),$('#registration_form3'));
            });
        }

        set_form(null, $('#registration_form1'));
        $('#registration_form2').hide();
        $('#registration_form3').hide();
        $('#registration_form4').hide();

        $('.datepicker').datepicker({dateFormat: 'yy-mm-dd'})
    });
</script>

app/views/users/_show.html.erb
<% provide(:title, 'Profile') %>
<div id="container">
  <div class="row">
    <div class="span3">
      <%= render :partial => 'users/user_contact' %>
      <%= render :partial => 'users/user_controls' %>
    </div>
    <div class="span9" id="response_area">
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal large fade" id="user_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"> </h4>
      </div>
      <div class="modal-body">

      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/_user_contact.html.erb
<% @user = (@customer || @employee) %>

<h4><%= @user.full_name %></h4>
<%= @user.full_address.html_safe %><br>
<br>
<br>
<table class="table table-striped">
  <tr>
    <th>Email:</th>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <th>Home Phone:</th>
    <td><%= @user.home_phone %></td>
  </tr>
  <tr>
    <th>Cell Phone:</th>
    <td><%= @user.cell_phone %></td>
  </tr>
  <tr>
    <th>Date of Birth:</th>
    <td><%= @user.dob.strftime('%m/%d/%Y') %></td>
  </tr>
</table>

<h5 id="balance_due"><%= sprintf 'Balance Due: $%.2f', @user.balance if @customer %></h5>

app/views/users/_user_controls.html.erb
<% if @customer %>
    <%= link_to customer_transactions_path(@customer), :id => 'new_payment', :remote => true do %>
        <button class="btn usr-ctrl">
          <img src="/images/home/transaction_hist.png" width="50" height="50" alt="Transaction History"/></button>
    <% end %>
    <%= link_to customer_enrollments_path(@customer), :id => 'view_enrollments', :remote => true do %>
        <button class="btn usr-ctrl"><img src="/images/home/courses.png" width="50" height="50" alt="Enrollment"/>
        </button>
    <% end %>
    <%= link_to edit_customer_path(@customer), :id => 'edit_user', :remote => true do %>
        <button class="btn usr-ctrl"><img src="/images/users/edit_item.png" width="50" height="50" alt="Edit Customer"/>
        </button>
    <% end %>
<% elsif @employee %>
    <%= link_to employee_sections_path(@employee), :id => 'view_sections', :remote => true do %>
        <button class="btn usr-ctrl">
          <img src="/images/home/course_mgmt.png" width="50" height="50" alt="Instructor Courses"/></button>
    <% end %>
    <%= link_to edit_employee_path(@employee), :id => 'edit_user', :remote => true do %>
        <button class="btn usr-ctrl"><img src="/images/users/edit_item.png" width="50" height="50" alt="Edit Employee"/>
        </button>
    <% end %>
<% end %>

<div id="button_title" style="position: absolute;
                              text-align: center;
                              font-size: large;
                              margin-top: 15px;
                              width: 163px;">

</div>

app/views/users/index.html.erb
<% provide(:title, 'People') %>
<%- model_class = User -%>

<div class="row">
  <table id="users_table" class="table table-condensed">
    <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Phone</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @users.all.each do |user| %>
        <tr id="<%= user.id %>">
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.cell_phone %></td>
          <td><%= link_to 'View Profile', user_path(user), :class => 'btn btn-mini btn-inverse' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

</div>