config/routes.rb
CARS::Application.routes.draw do
  root "home#index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  resources :users, only: [:index, :show]

  resources :enrollments do
   resources :attendances
   resources :course_progresses
  end

  resources :sections do
    resources :enrollments
    resources :attendances do
      collection do
        post 'take'
      end
    end
  end

  resources :employees, except: [:index, :new, :create, :destroy] do
    resources :sections
  end

  resources :customers, except: [:index, :new, :create, :destroy] do
    resources :transactions do
      resource :transactions
    end
    resources :enrollments do
      resources :attendances
    end
  end

  resources :courses do
    resources :sections, :course_prerequisites, :instruction_units
  end

  

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :customer
  belongs_to :section
  has_many :attendances
  belongs_to :transaction

  validates_presence_of :customer
  validates_presence_of :section
  validates_uniqueness_of :customer, :scope => :section, :message => 'already enrolled in this section'
  validate :prerequisites_met?

  after_create :log_enrollment_transaction
  after_destroy :log_unenrollment_transaction


  def prerequisites_met?
    course           = section.course
    customer_courses = []

    #get a list of all classes customer has taken
    customer.enrollments.each do |enrollment|
      customer_courses.push(enrollment.section.course)
    end

    #get a list of prerequisites and check if customer has taken them
    course.prerequisites(true).each do |prereq|
      rule = CoursePrerequisite.where(:course => course, :prerequisite => prereq).take
      if rule && !rule.allow_concurrent?
        if !customer_courses.include? prereq
          errors.add(:section, "Prerequisite Not Taken! (#{prereq.name})")
        else
          units_taken = []
          #iterate through all instruction units taken by customer
          customer.course_progresses.each do |unit|
            if unit.section.course == prereq
              #the instruction unit is part of the prereq course
              units_taken.push(unit)
            end
          end

          #check all prereq instruction units have been completed
          prereq.instruction_units.all.each do |piu|
            if !units_taken.include? piu
              errors.add(:section, "Prerequisite Not Complete! (#{prereq.name})")
              break
            end
          end

        end
      #check that the customer is currently enrolled in the prerequisite if concurreny allowed
      elsif rule && rule.allow_concurrent?
        if !customer_courses.include? prereq
          errors.add(:section, "Must enroll in #{prereq.name} first!")
        end
      end

      course = prereq
    end
  end

  def log_enrollment_transaction
    t                  = Transaction.new
    t.customer         = customer
    t.transaction_type = TransactionType.find_by_name('Enroll In Course')
    t.amount           = section.course.cost
    t.date             = Date.today
    t.description      = "Enrolled in #{section.course.name}"
    t.payment_method   = nil
    t.transaction_id   = nil
    t.save!
    self.update(:transaction => t)
  end

  def log_unenrollment_transaction
    t                  = Transaction.new
    t.customer         = customer
    t.transaction_type = TransactionType.find_by_name('Unenroll From Course')
    t.amount           = calculate_refund_amount
    t.date             = Date.today
    if t.amount == 0
      t.description    = "Unenrolled from #{section.course.name} - No Refund"
    else
      t.description    = "Unenrolled from #{section.course.name}"
    end
    t.payment_method   = nil
    t.transaction      = transaction
    t.save!
  end

  def calculate_refund_amount
    start_date  = section.start_time
    gets_refund = Date.today - 5.days < start_date
    gets_refund ? transaction.amount_owed * -1 : 0
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_filter do
    @customer = nil
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
    end
    if params[:section_id]
      @section = Section.find(params[:section_id])
    end
  end

  # GET /enrollments
  # GET /enrollments.json
  def index
    if params[:customer_id]
      @enrollments = Enrollment.where(:customer_id => @customer.id)
    elsif params[:section_id]
      @enrollments = Enrollment.where(:section_id => @section.id)
    else
      @enrollments = Enrollment.all
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)
    @enrollment.customer = @customer

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to customer_enrollment_path(@customer), notice: 'Enrollment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @enrollment }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
        format.js   { render action: 'new'}
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:customer_id, :section_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_customer_index.html.erb
<% if !@enrollments.empty? %>
    <table class="table table-condensed table-hover">
      <caption><h4>Current Enrollment</h4></caption>
      <thead>
      <tr>
        <th>Instructor</th>
        <th>Course</th>
      </tr>
      </thead>

      <tbody>
      <% @enrollments.each do |enrollment| %>
          <tr>
            <td><%= enrollment.section.employee.full_name %></td>
            <td><%= enrollment.section.course.name %></td>
            <td>
              <div class="btn-group">
                <%= link_to 'Details', customer_enrollment_path(enrollment.customer, enrollment), :class => 'btn btn-mini btn-inverse', :remote => true %>
                <%= link_to 'Unenroll',customer_enrollment_path(enrollment.customer, enrollment), :class => 'btn btn-mini btn-inverse', method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
              </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>
<% else %>
    <div style="text-align: center"><h4>No Enrollments</h4></div>
<% end %>
<% if @customer %>
    <div style="text-align: center">
      <%= link_to 'Enroll In A New Course', new_customer_enrollment_path(@customer), :class => 'btn btn-inverse', :remote => true %>
    </div>
<% end %>

app/views/enrollments/_customer_show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-condensed table-hover">
  <thead>
  <tr>
    <th>Instructor</th>
    <th>Location</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Times</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @enrollment.section.employee.full_name %></td>
    <td><%= @enrollment.section.location.address %></td>
    <td><%= @enrollment.section.start_time.strftime('%m/%d/%Y') %></td>
    <td><%= @enrollment.section.end_time.strftime('%m/%d/%Y') %></td>
    <td><%= @enrollment.section.start_time.strftime('%H:%M') + ' - ' + @enrollment.section.end_time.strftime('%H:%M') %></td>
  </tr>
  </tbody>
</table>

<div>
  <h4>Course Progress</h4>
  <%-
      #
      #The controller action is not run when rendering a partial.
      #
      @not_taken        = InstructionUnit.where(:course => @enrollment.section.course).all
      @completed_units  = CourseProgress.where(:section => @enrollment.section, :customer => @enrollment.customer).all
      @completed_units.each do |cp|
        @not_taken.delete_if {|nt| nt == cp.instruction_unit}
      end

  %>
  <%= render :template => 'course_progresses/index.html.erb', :locals => {:@completed_units => @completed_units,
                                                                          :@not_taken       => @not_taken} %>
</div>

app/views/enrollments/_employee_index.html.erb
<div id="enrollments_table">
  <% if !@enrollments.empty? %>
      <table class="table table-condensed table-hover">
        <caption><h4>Current Enrollment</h4></caption>
        <thead>
        <tr>
          <th>Customer</th>
          <th>Course</th>
        </tr>
        </thead>

        <tbody>
        <% @enrollments.each do |enrollment| %>
            <tr>
              <td><%= enrollment.customer.full_name %></td>
              <td><%= @section.course.name %></td>
              <td>
                <div class="btn-group">
                  <%= link_to 'Details', section_enrollment_path(enrollment.section, enrollment), :class => 'btn btn-mini btn-inverse', :remote => true %>
                  <%= link_to 'Drop From Course', section_enrollment_path(enrollment.section, enrollment), :class => 'btn btn-mini btn-inverse', method: :delete, data: {confirm: 'Are you sure?'}, :remote => true %>
                </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
      <div style="text-align: center"><h4>No Enrollments</h4></div>
  <% end %>
</div>
<div style="text-align: center">
  <%= link_to 'Back To Sections', employee_sections_path(@section.employee), :class => 'btn btn-mini btn-inverse', :remote => true %>
</div>

app/views/enrollments/_employee_show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-condensed table-hover">
  <thead>
  <tr>
    <th>Location</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Times</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @enrollment.section.location.address %></td>
    <td><%= @enrollment.section.start_time.strftime('%m/%d/%Y') %></td>
    <td><%= @enrollment.section.end_time.strftime('%m/%d/%Y') %></td>
    <td><%= @enrollment.section.start_time.strftime('%H:%M') + ' - ' + @enrollment.section.end_time.strftime('%H:%M') %></td>
  </tr>
  </tbody>
</table>

<div>
  <h4>Attendance History</h4>
  <%= render :partial => 'attendances/employee_index', :locals => {:@attendances => @enrollment.attendances} %>
</div>

app/views/enrollments/_form.html.erb
<%= form_for [@customer, @enrollment], :remote => true do |f| %>
    <% if @enrollment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

          <ul>
            <% @enrollment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :section_id %>
      <br>
      <%= f.hidden_field :section_id %>
      <select class="courses">
      <% Course.all.each do |course| %>
        <option value="<%= course_sections_path(course) %>">
          <%= course.name %>
        </option>
      <% end %>
      </select>

      <div id="sections_response_area">

      </div>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/enrollments/create.js.erb
$('#user_modal').modal('hide');
$('#view_enrollments').click();
$.ajax({
    url: '<%= customer_path(@customer) %>',
    complete: function(xhr){
        var response = $($.parseHTML(xhr.responseText)).find('#balance_due').html()
        $('#balance_due').html(response);
    }
});

app/views/enrollments/destroy.js.erb
<% if @customer %>
//called from the customer profile. refresh data
$('#view_enrollments').click();
$.ajax({
    url: '<%= customer_path(@customer) %>',
    complete: function (xhr) {
        var response = $($.parseHTML(xhr.responseText)).find('#balance_due').html();
        $('#balance_due').html(response);
    }
});
<% else %>
//called from the employee profile. reload the sections/enrollments view
$.ajax({
    url: '<%= section_enrollments_path(@section) %>',
    complete: function (xhr) {
        var response = $($.parseHTML(xhr.responseText)).find('#enrollments_table').html();
        $('#response_area').html(response);
        console.log(response)
    }
});
<% end %>

app/views/enrollments/edit.html.erb
<h3>Editing enrollment</h3>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<% if @customer %>
    <%= render 'customer_index' %>
<% else %>
    <%= render 'employee_index'  %>
<% end %>

app/views/enrollments/index.js.erb
$(document).ready(function(){

    $('#response_area').html('<%= j render :template => 'enrollments/index.html.erb' %>')

});

app/views/enrollments/new.html.erb
<%= render 'form' %>

app/views/enrollments/new.js.erb
$(document).ready(function(){
    function refreshTable(url){
        $.ajax({
            url: url,
            dataType: 'html',
            complete: function(xhr){
                var response = $($.parseHTML(xhr.responseText)).find('#sections').html()
                //console.log(response)
                $('#sections_response_area').html(response)
                var id = parseInt($('#enrollment_section_id').val(), 0)
                $('#sections_body tr').each(function(){
                    if($(this).attr('id') == id){
                        $(this).toggleClass('alert-success')
                    }else{
                        $(this).removeClass('alert-success')
                    }
                });
                $('#sections_body tr').on('click', function(){
                    var id = $(this).attr('id')
                    $('#enrollment_section_id').val(id)
                    $('#sections_body tr').each(function(){
                        if($(this).attr('id') == id){
                            $(this).toggleClass('alert-success')
                        }else{
                            $(this).removeClass('alert-success')
                        }
                    });
                })
            }
        });
    }
    var form = '<%= j render :template => 'enrollments/new.html.erb' %>'
    var title = '<%= "Enroll #{@customer.first_name} In New Course" %>'
    $('.modal-title').html(title)
    $('.modal-body').html(form)
    $('#user_modal').modal()

    $('.courses').on('change', function(){
        var url = $(this).val();
        refreshTable(url)
    });

    refreshTable('<%= course_sections_path(Course.first)%>')
});

app/views/enrollments/show.html.erb
<% if @customer %>
    <%= render 'customer_show' %>
<% else %>
    <%= render 'employee_show'  %>
<% end %>

app/views/enrollments/show.js.erb
$(document).ready(function(){
    var form = '<%= j render :template => 'enrollments/show.html.erb' %>'
    var title = '<%= "Enrollment Info" %>'
    $('.modal-title').html(title)
    $('.modal-body').html(form)
    $('#user_modal').modal()
});