config/routes.rb
CARS::Application.routes.draw do
  root "home#index"
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  resources :users, only: [:index, :show]

  resources :enrollments do
   resources :attendances
   resources :course_progresses
  end

  resources :sections do
    resources :enrollments
    resources :attendances do
      collection do
        post 'take'
      end
    end
  end

  resources :employees, except: [:index, :new, :create, :destroy] do
    resources :sections
  end

  resources :customers, except: [:index, :new, :create, :destroy] do
    resources :transactions do
      resource :transactions
    end
    resources :enrollments do
      resources :attendances
    end
  end

  resources :courses do
    resources :sections, :course_prerequisites, :instruction_units
  end

  

end

app/models/transaction_type.rb
class TransactionType < ActiveRecord::Base
  has_many :transactions
  validates :name, :presence => true, :uniqueness => true
  validates_numericality_of :due_in_days, :greater_than_or_equal_to => 0
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_filter do
    @customer = Customer.find(params[:customer_id])
    @parent_transaction = nil
    if params[:transaction_id]
      @parent_transaction = Transaction.find(params[:transaction_id])
    end
  end

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all.where(:customer_id => @customer.id)
    respond_to do |format|
      format.html {redirect_to :root, :notice => 'Transactions must be viewed from your profile.'}
      format.js
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    respond_to do |format|
      format.html {redirect_to :root, :notice => 'Transactions must be viewed from your profile.'}
      format.js
    end
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @transaction.transaction_id = @parent_transaction
    respond_to do |format|
      format.html{redirect_to :root, :notice => 'Transactions must be created from your profile.'}
      format.js
    end
  end

  # GET /transactions/1/edit
  def edit
    respond_to do |format|
      format.html{redirect_to :root, :notice => 'Transactions cannot be edited.'}
      format.js
    end
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.customer = @customer
    @transaction.transaction = @parent_transaction
    @transaction.amount *= -1
    @transaction.transaction_type = TransactionType.find_by_name('Payment Towards Balance')
    @transaction.date = Date.today

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to :back, notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: customer_transaction_path(@customer, @transaction) }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
        format.js   { render :action => 'new'}
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:transaction_type_id, :amount, :date, :description, :payment_method_id, :transaction_id, :customer_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for [@customer, @parent_transaction, @transaction], :remote =>true do |f| %>
    <% if @transaction.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

          <ul>
            <% @transaction.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :payment_method_id %>
      <br>
      <%= f.collection_select :payment_method_id, PaymentMethod.all, :id, :name %>
    </div>
    <div class="field">
      <%= f.label :amount %>
      <br>
      <h6>$<%= f.text_field :amount %></h6>
    </div>
    <div class="field">
      <%= f.label :description %>
      <br>
      <%= f.text_area :description, :value => 'Payment On - ' + @parent_transaction.description %>
    </div>
    <div class="actions">
      <%= f.submit 'Make Payment', :class => 'btn btn-large btn-primary' %>
    </div>
<% end %>

app/views/transactions/create.js.erb
$('#user_modal').modal('hide');
$('#new_payment').click();
$.ajax({
    url: '<%= customer_path(@customer) %>',
    complete: function(xhr){
        var response = $($.parseHTML(xhr.responseText)).find('#balance_due').html()
        $('#balance_due').html(response);
    }
});

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', customer_transaction_path(@customer) %> |
<%= link_to 'Back', customer_transactions_path(@customer) %>

app/views/transactions/index.html.erb
<% if !@transactions.empty? %>
<table id="transactions_table" class="table table-condensed">
  <caption><h4>Transaction History</h4></caption>
  <thead>
  <tr>
    <th>Transaction Date</th>
    <th>Description</th>
    <th>Type</th>
    <th>Amount</th>
    <th>Balance Due</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @transactions.each do |trans| %>
      <% klass = trans.transaction_id.nil? ? trans.id.to_s + ' parent' : trans.transaction_id.to_s + ' child' %>
      <tr class="<%= klass %>">
        <td class="date"><%= trans.date.strftime('%m/%d/%Y') %></td>
        <td class="description"><%= trans.description %></td>
        <td class="transaction_type"><%= trans.transaction_type.name %></td>
        <td class="amount"><%= sprintf('$%.2f', trans.amount) %></td>
        <td class="amount_owed">
          <% if !trans.transaction_id %>
              <%= sprintf('$%.2f', trans.amount_owed) %>
          <% end %>
        </td>
        <td>
          <% if !trans.transaction_id && trans.amount_owed > 0.0 %>
            <%= link_to new_customer_transaction_transactions_path(@customer, trans), :remote => true do %>
                <button class="btn btn-mini btn-inverse">Make Payment</button>
            <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<% else %>
    <div style="text-align: center"><h4>No Transactions</h4></div>
<% end %>

app/views/transactions/index.js.erb
$(document).ready(function () {
    var selected_transaction_id = null;

    function setTransaction(transaction_id) {
        selected_transaction_id = transaction_id;
    };

    $('#response_area').html('<%= j render :template => 'transactions/index.html.erb' %>')

    $('#transactions_table tbody tr .btn').css('opacity', 0);

    $('#transactions_table tbody tr').hover(
            function () {
                var klass = $(this).attr('class')
                var id = klass.substring(0, klass.indexOf(' '));
                $('#transactions_table tbody tr').each(function () {
                    if ($(this).hasClass('parent') && $(this).hasClass(id)) {
                        $(this).toggleClass('alert-error');
                        $(this).find('button').css('opacity', 1);
                        setTransaction(id);
                    }
                    else if ($(this).hasClass('child') && $(this).hasClass(id)) {
                        $(this).toggleClass('alert-success');
                    }
                });
            },
            function () {
                var klass = $(this).attr('class')
                var id = klass.substring(0, klass.indexOf(' '));
                $('#transactions_table tbody tr').each(function () {
                    if ($(this).hasClass('parent') && $(this).hasClass(id)) {
                        $(this).toggleClass('alert-error');
                        $(this).find('button').css('opacity', 0);
                    }
                    else if ($(this).hasClass('child') && $(this).hasClass(id)) {
                        $(this).toggleClass('alert-success');
                    }
                });
            }
    );

});

app/views/transactions/new.html.erb
<%= render 'form' %>

app/views/transactions/new.js.erb
$(document).ready(function(){
    var form = '<%= j render :template => 'transactions/new.html.erb' %>'
    var title = '<%= 'Make Payment - ' + @parent_transaction.description %>' + ' – Balance Due: '
               + '<%= sprintf('$%0.2f',@parent_transaction.amount_owed) %>'
    $('.modal-title').html(title)
    $('.modal-body').html(form)
    $('#transaction_amount').val('')
    $('#user_modal').modal()
});

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction type:</strong>
  <%= @transaction.transaction_type_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @transaction.payment_method_id %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @transaction.transaction_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @transaction.customer_id %>
</p>

<%= link_to 'Edit', edit_customer_transaction_path(@customer, @transaction) %> |
<%= link_to 'Back', customer_transactions_path(@customer) %>